[[admins]]
login = "test-admin-1"
password = "test-admin-password-1"

[[admins]]
login = "test-admin-2"
password = "test-admin-password-2"

[[users]]
login = "test-user-1"
password = "test-password-1"

[[users]]
login = "test-user-2"
password = "test-password-2"

[[users]]
login = "test-user-3"
password = "test-password-3"
